# Generated by Django 5.1.6 on 2025-03-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'time']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['platform']},
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('twitch', 'Twitch'), ('youtube', 'YouTube'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('discord', 'Discord')], max_length=20),
        ),
    ]
